Models/Models/LoginView.cs
using System.ComponentModel.DataAnnotations;

namespace Sintronico.Models;
public class LoginView
{

    [DataType(DataType.EmailAddress)]
    public String Usuario {get;set;}

    [DataType(DataType.Password)]
    public String Clave {get;set;}

}

Controllers/BicicletaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sintronico.Models;

namespace Sintronico.Controllers
{
    public class BicicletaController : Controller
    {
        private IRepositorioBicicleta repositorio;
        private IRepositorioPropietario RepositorioPropietario;

        public BicicletaController(IRepositorioBicicleta repositorio,IRepositorioPropietario RepositorioPropietario)
        {
            this.repositorio = repositorio;
            this.RepositorioPropietario = RepositorioPropietario;
        }

        // GET: Bicicleta
        public ActionResult Index()
        {
            var lista = repositorio.ObtenerBicicletas();
            return View(lista);
        }

        // GET: Bicicleta/Details/5
        public ActionResult Detalles(int id)
        {
            var lista = repositorio.ObtenerBicicleta(id);
            return View(lista);
        }

        // GET: Bicicleta/Create
        public ActionResult Create()
        {
            ViewBag.Propietario = RepositorioPropietario.ObtenerPropietarios();
            return View();
        }

        // POST: Bicicleta/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Bicicleta bicicleta)
        {
            try
            {
                var res = repositorio.Alta(bicicleta);

                if(res > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
                
            }
            catch
            {
                return View();
            }
        }

        // GET: Bicicleta/Edit/5
        public ActionResult Editar(int id)
        {
            ViewBag.Propietario = RepositorioPropietario.ObtenerPropietarios();
            var lista = repositorio.ObtenerBicicleta(id);
            return View(lista);
        }

        // POST: Bicicleta/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(int id, IFormCollection collection)
        {
            try
            {   
                var b = repositorio.ObtenerBicicleta(id);
                b.IdPropietario = Int32.Parse(collection["IdPropietario"]);
                b.Marca = collection["Marca"];
                b.Color = collection["Color"];
                b.NumeroSerie = collection["NumeroSerie"];
                b.Tipo = collection["Tipo"];
                b.Imagen = collection["Imagen"];

                var res = repositorio.Editar(b);

                if (res > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
            }
            }
            catch
            {
                return View();
            }
        }

        // GET: Bicicleta/Delete/5
        public ActionResult Eliminar(int id)
        {
            var lista = repositorio.ObtenerBicicleta(id);
            return View(lista);
        }

        // POST: Bicicleta/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(int id, IFormCollection collection)
        {
            try
            {
                var res = repositorio.Baja(id);

                if(res > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/PagosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sintronico.Models;

namespace Sintronico.Controllers
{
    public class PagosController : Controller
    {
        private IRepositorioPago repositorioPagos;
        private IRepositorioPresupuesto repositorioPresupuesto;

        public PagosController(IRepositorioPago repositorioPagos, IRepositorioPresupuesto repositorioPresupuesto)
        {
            this.repositorioPagos = repositorioPagos;
            this.repositorioPresupuesto = repositorioPresupuesto;
        }

        // GET: Pagos
        public ActionResult Index()
        {
            var lista = repositorioPagos.ObtenerPagos();
            return View(lista);
        }

        // GET: Pagos/Details/5
        public ActionResult Detalles(int id)
        {
            var lista = repositorioPagos.ObtenerPago(id);
            return View(lista);
        }

        // GET: Pagos/Create
        public ActionResult Create()
        {
            ViewBag.Presupuesto = repositorioPresupuesto.ObtenerPresupuestos();
            return View();
        }

        // POST: Pagos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pago pago)
        {
            try
            {
                var res = repositorioPagos.Alta(pago);

                if(res > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }                
            }
            catch
            {
                return View();
            }
        }

        // GET: Pagos/Edit/5
        public ActionResult Editar(int id)
        {
            ViewBag.Presupuesto = repositorioPresupuesto.ObtenerPresupuestos();
            var lista = repositorioPagos.ObtenerPago(id);
            return View(lista);
        }

        // POST: Pagos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(int id, IFormCollection collection)
        {
            try
            {
                var pago = new Pago();
                pago.IdPresupuesto = Int32.Parse(collection["IdPresupuesto"]);
                pago.FechaEmision = DateTime.Parse(collection["FechaEmision"]);
                pago.Monto = Double.Parse(collection["Monto"]);

                var res = repositorioPagos.Editar(pago);

                if(res > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Pagos/Delete/5
        public ActionResult Eliminar(int id)
        {
            var lista = repositorioPagos.ObtenerPago(id);
            return View(lista);
        }

        // POST: Pagos/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(int id, IFormCollection collection)
        {
            try
            {
                var res = repositorioPagos.Baja(id);

                if(res > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sintronico.Models;

namespace Sintronico.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IConfiguration configuration;
        private IRepositorioUsuario repositorioUsuario;

        public UsuarioController(IConfiguration configuration, IRepositorioUsuario repositorioUsuario)
        {
            this.configuration = configuration;
            this.repositorioUsuario = repositorioUsuario;
        }

        // GET: Usuario
        public ActionResult Index()
        {
            var lista = repositorioUsuario.ObtenerUsuarios();
            return View(lista);
        }

        // GET: Usuario/Details/5
        public ActionResult Detalles(int id)
        {
            var lista = repositorioUsuario.ObtenerUsuario(id);
            return View(lista);
        }

        // GET: Usuario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuario/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuario usuario)
        {
            try
            {
                String hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                        password: usuario.Clave,
                        salt : System.Text.Encoding.ASCII.GetBytes(configuration["salt"]),
                        prf : KeyDerivationPrf.HMACSHA1,
                        iterationCount : 1000,
                        numBytesRequested : 256 / 8 
                    ));
                
                usuario.Clave = hashed;
                
                var res = repositorioUsuario.Alta(usuario);

                if(res > 0 )
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
                
            }
            catch
            {
                return View();
            }
        }

        // GET: Usuario/Edit/5
        public ActionResult Editar(int id)
        {
            var lista = repositorioUsuario.ObtenerUsuario(id);
            return View(lista);
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(int id, IFormCollection collection)
        {
            try
            {
                var usuario = repositorioUsuario.ObtenerUsuario(id);
                usuario.Nombre = collection["Nombre"];
                usuario.Apellido = collection["Apellido"];
                usuario.Email = collection["Email"];
                usuario.Clave = collection["Clave"];
                usuario.Avatar = collection["Avatar"];
                usuario.Rol = Int32.Parse(collection["Rol"]);

                var res = repositorioUsuario.Editar(usuario);

                if(res > 0 )
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Usuario/Delete/5
        public ActionResult Eliminar(int id)
        {
            var lista = repositorioUsuario.ObtenerUsuario(id);
            return View(lista);
        }

        // POST: Usuario/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(int id, IFormCollection collection)
        {
            try
            {
                var res = repositorioUsuario.Baja(id);

                if(res > 0 )
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Login(String returnUrl)
        {
            TempData["returnUrl"] = returnUrl;
            return View();
        } 

        // POST : Usuario/Login/
        [HttpPost]
        public async Task<IActionResult> Login(LoginView login)
        {
            try
            {
                var returnUrl = String.IsNullOrEmpty(TempData["returnUrl"] as String)? "/Home" : TempData["returnUrl"].ToString();
                if(ModelState.IsValid)
                {
                    String hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                        password: login.Clave,
                        salt : System.Text.Encoding.ASCII.GetBytes(configuration["salt"]),
                        prf : KeyDerivationPrf.HMACSHA1,
                        iterationCount : 1000,
                        numBytesRequested : 256 / 8 
                    ));

                    Usuario user = repositorioUsuario.ObtenerUsuarioPorEmail(login.Usuario);
                    if(user == null || user.Clave != hashed)
                    {
                        ModelState.AddModelError("","El email o la clave ingresada es invalida");
                        TempData["returnUrl"] = returnUrl;
                        return View();
                    }

                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, user.Email),
                        new Claim("FullName", user.Nombre + " " + user.Apellido),
                        new Claim(ClaimTypes.Role, user.RolNombre),
                    };

                    var claimsIdentity = new ClaimsIdentity(
                        claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity));

                    TempData.Remove(returnUrl);
                    return Redirect(returnUrl);
                }
                TempData["returnUrl"] = returnUrl;
                return Redirect(returnUrl);
            }
            catch(Exception ex)
            {
                throw;
            }
        }


        [Route("salir", Name = "logout")]
        public async Task<ActionResult> Logout()
        {
            await HttpContext.SignOutAsync(
                CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sintronico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sintronico.styles.css" asp-append-version="true" />
</head>
<body>
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Sintronico</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if( !User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a> 

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Usuario" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Propietario" asp-action="Index">Propietario</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Bicicleta" asp-action="Index">Bicicleta</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Presupuesto" asp-action="Index">Presupuesto</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Repuestos" asp-action="Index">Repuesto</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Pagos" asp-action="Index">Pago</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Usuario" asp-action="Index">Usuario</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Usuario" asp-action="Logout">Cerrar sesión</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>



    <div id="hero">
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Sintronico - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Login.cshtml
@model Sintronico.Models.LoginView

<hr />
<div class="login container text-center">
    <div class="imagenLogin container">
        <img src="" alt="" class="imagen">
    </div>
    <h4 class="text-center p-3 text-light">Iniciar Sesion</h4>
    <div class="d-flex text-light justify-content-center p-3">
        <form asp-controller="Usuario" asp-action="Login">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group p-2">
                <label asp-for="Usuario" class="control-label"></label>
                <input asp-for="Usuario" class="form-control" />
                <span asp-validation-for="Usuario" class="text-danger"></span>
            </div>
            <div class="form-group p-2 col-12">
                <label asp-for="Clave" class="control-label"></label>
                <input asp-for="Clave" class="form-control" />
                <span asp-validation-for="Clave" class="text-danger"></span>
            </div>
            <div>
                <a href="" class="olvidado">Has olvidado la contraseña?</a>
            </div>
            <div class="boton p-2">
                <input type="submit" value="Iniciar sesión" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<hr />


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}