Models/Models/Presupuesto.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sintronico.Models;

public class Presupuesto
{  
    [Display(Name = "Cod. Presupuesto")]
    [Key]
    public int IdPresupuesto {get;set;}

    [Display(Name = "Bicicleta")]
    public int IdBicicleta {get;set;}

    [Display(Name = "Bicicleta")]
    [ForeignKey(nameof(IdBicicleta))]
    public Bicicleta? Bicicleta {get;set;}

    [Display(Name = "Fecha de Inicio")]
    public DateTime FechaInicio {get;set;}

    [Display(Name = "Fecha de Entrega")]
    public DateTime FechaEntrega {get;set;}

    public Double Monto {get;set;}

    public string Estado {get;set;}
}

Controllers/DetallePresupuestoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sintronico.Models;

namespace Sintronico.Controllers
{
    public class DetallePresupuestoController : Controller
    {

        private IRepositorioDetallePresupuestos repositorio;
        private IRepositorioRepuesto repositorioRepuesto;
        private IRepositorioPresupuesto repositorioPresupuesto;
 
        public DetallePresupuestoController(IRepositorioDetallePresupuestos repositorio, IRepositorioRepuesto repositorioRepuesto, IRepositorioPresupuesto repositorioPresupuesto)
        {
            this.repositorio = repositorio;
            this.repositorioRepuesto = repositorioRepuesto;
            this.repositorioPresupuesto = repositorioPresupuesto;
        }

        // GET: DetallePresupuesto
        public ActionResult Index(int id)
        {
            var lista = repositorio.ObtenerDetallePresupuestos(id);
            ViewBag.IdPresupuesto = id;
            return View(lista);
        }

        // GET: DetallePresupuesto/Details/5
        public ActionResult Detalles(int id)
        {
            var lista = repositorio.ObtenerDetallePresupuesto(id);
            return View(lista);
        }

        // GET: DetallePresupuesto/Create
        public ActionResult CreateArreglo()
        {
            ViewBag.Presupuesto = repositorioPresupuesto.ObtenerPresupuestos();
            return View();
        }

               // POST: DetallePresupuesto/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateArreglo(DetallePresupuesto detalle)
        {
            try
            {
                var res = repositorio.Alta(detalle);
 
                if(res > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
                
            }
            catch
            {
                return View();
            }
        }

        public ActionResult CreateRepuesto(int id)
        {
            ViewBag.Repuestos = repositorioRepuesto.ObtenerRepuestos();
            ViewBag.IdPresupuesto = id;
            return View();
        }

        // POST: DetallePresupuesto/Create 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRepuesto(DetallePresupuesto detalle)
        {
            try
            {
                var repuesto = repositorioRepuesto.ObtenerRepuesto(detalle.IdRepuesto);
                detalle.Total = repuesto.Monto * detalle.Cantidad;
                var res = repositorio.Alta(detalle);
 
                if(res > 0)
                {
                    return RedirectToAction(nameof(Index),new {id = detalle.IdPresupuesto});
                }
                else
                {
                    return View();
                }
                
            }
            catch
            {
                return View();
            }
        }

        // GET: DetallePresupuesto/Edit/5
        public ActionResult Editar(int id)
        {
            ViewBag.Repuestos = repositorioRepuesto.ObtenerRepuestos();
            ViewBag.Presupuesto = repositorioPresupuesto.ObtenerPresupuestos();
            var lista = repositorio.ObtenerDetallePresupuesto(id);
            return View(lista);
        }

        // POST: DetallePresupuesto/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(int id, IFormCollection collection)
        {
            try
            {
                var detalle = repositorio.ObtenerDetallePresupuesto(id);
                detalle.IdRepuesto = Int32.Parse(collection["IdRepuesto"]);
                detalle.IdPresupuesto = Int32.Parse(collection["IdPresupuesto"]);
                detalle.Total = Double.Parse(collection["Total"]);
                detalle.Cantidad = Int32.Parse(collection["Cantidad"]);

                var res = repositorio.Editar(detalle);

                if(res > 0)
                {
                    return RedirectToAction(nameof(Index),new {id = detalle.IdPresupuesto});
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: DetallePresupuesto/Delete/5
        public ActionResult Eliminar(int id)
        {
            var lista = repositorio.ObtenerDetallePresupuesto(id);
            ViewBag.IdPresupuesto = lista.IdPresupuesto;
            return View(lista);
        }

        // POST: DetallePresupuesto/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(int id, IFormCollection collection)
        {
            try
            {
                var res = repositorio.Baja(id);

                if(res > 0)
                {
                    return RedirectToAction(nameof(Index),new {id = collection["IdPresupuesto"]});
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/PresupuestoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sintronico.Models;

namespace Sintronico.Controllers
{
    public class PresupuestoController : Controller
    {
        private IRepositorioPresupuesto repositorio;
        private IRepositorioBicicleta repositorioBicicleta;

        public PresupuestoController(IRepositorioPresupuesto repositorio, IRepositorioBicicleta repositorioBicicleta)
        {
            this.repositorio = repositorio;
            this.repositorioBicicleta = repositorioBicicleta;
        }
        // GET: Presupuesto
        public ActionResult Index()
        {
            var lista = repositorio.ObtenerPresupuestos();
            return View(lista);
        }

        // GET: Presupuesto/Details/5
        public ActionResult Detalles(int id)
        {
            var lista = repositorio.ObtenerPresupuesto(id);
            return View(lista);
        }

        // GET: Presupuesto/Create
        public ActionResult Create()
        {
            ViewBag.Bicicletas = repositorioBicicleta.ObtenerBicicletas();
            return View();
        }

        // POST: Presupuesto/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Presupuesto Presupuesto)
        {
            try
            {
                var res = repositorio.Alta(Presupuesto);
                if(res > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Presupuesto/Edit/5
        public ActionResult Editar(int id)
        {
            var lista = repositorio.ObtenerPresupuesto(id);
            return View(lista);
        }

        // POST: Presupuesto/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(int id, IFormCollection collection)
        {
            try
            {
                var p = repositorio.ObtenerPresupuesto(id);
                p.IdBicicleta = Int32.Parse(collection["IdBicicleta"]);
                p.FechaInicio = DateTime.Parse(collection["FechaInicio"]) ;
                p.FechaEntrega = DateTime.Parse(collection["FechaEntrega"]);
                p.Monto = Double.Parse(collection["Monto"]);
                p.Estado = collection["Estado"];

                var res = repositorio.Editar(p);

                if(res > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Presupuesto/Delete/5
        public ActionResult Eliminar(int id)
        {
            var lista = repositorio.ObtenerPresupuesto(id);
            return View(lista);
        }

        // POST: Presupuesto/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(int id, IFormCollection collection)
        {
            try
            {
                var res = repositorio.Baja(id);

                if(res > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Presupuesto/Create.cshtml
@model Sintronico.Models.Presupuesto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Presupuesto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdBicicleta" class="control-label"></label>
                <select name="IdBicicleta" class="form-control">
                    @foreach (var item in (List<Bicicleta>)ViewBag.Bicicletas)
                    {
                        <option value="@item.IdBicicleta">@(item.Marca)</option>
                    }
                </select>
                <span asp-validation-for="IdBicicleta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaEntrega" class="control-label"></label>
                <input asp-for="FechaEntrega" class="form-control" />
                <span asp-validation-for="FechaEntrega" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Monto" class="control-label"></label>
                <input asp-for="Monto" class="form-control" />
                <span asp-validation-for="Monto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <select name="Estado" class="form-control">
                    <option value="Recibida" selected>Recibida</option>
                    <option value="En espera de aprobacion">En espera de aprobacion</option>
                    <option value="En cola">En cola</option>
                    <option value="En Reparacion">En Reparacion</option>
                    <option value="Para Entregar">Para Entregar</option>
                </select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Presupuesto/Detalles.cshtml
@model Sintronico.Models.Presupuesto

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<div>
    <h4>Presupuesto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdBicicleta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdBicicleta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaEntrega)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaEntrega)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Monto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Monto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Presupuesto/Editar.cshtml
@model Sintronico.Models.Presupuesto

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Presupuesto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdBicicleta" class="control-label"></label>
                <input asp-for="IdBicicleta" class="form-control" />
                <span asp-validation-for="IdBicicleta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaEntrega" class="control-label"></label>
                <input asp-for="FechaEntrega" class="form-control" />
                <span asp-validation-for="FechaEntrega" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Monto" class="control-label"></label>
                <input asp-for="Monto" class="form-control" />
                <span asp-validation-for="Monto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Presupuesto/Eliminar.cshtml
@model Sintronico.Models.Presupuesto

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Presupuesto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdBicicleta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdBicicleta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaEntrega)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaEntrega)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Monto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Monto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Eliminar">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Presupuesto/Index.cshtml
@model IEnumerable<Sintronico.Models.Presupuesto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPresupuesto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdBicicleta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaEntrega)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Monto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPresupuesto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bicicleta.IdBicicleta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaEntrega)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.IdPresupuesto }) |
                @Html.ActionLink("Detalles", "Index","DetallePresupuesto", new { id = item.IdPresupuesto }) |
                @Html.ActionLink("Eliminar", "Eliminar", new { id = item.IdPresupuesto })
            </td>
        </tr>
}
    </tbody>
</table>